# Generated by Django 5.0.4 on 2025-12-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hospital_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='patient_age',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='patient_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
